include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    todo: ignore
    fixme: ignore
    invalid_annotation_target: ignore
  exclude:
    - generated_plugin_registrant.dart
    - "**/*.freezed.dart"
    - "**/*.g.dart"
    - "**/*.config.dart"
    - "lib/generated/**"
linter:
  rules:
    - prefer_relative_imports
    - sort_child_properties_last
    - file_names
    - join_return_with_assignment
    - prefer_mixin
    - sort_constructors_first
    # - sort_unnamed_constructors_first
    - avoid_classes_with_only_static_members
    - always_put_control_body_on_new_line
    - avoid_empty_else
    - avoid_init_to_null
    - avoid_unused_constructor_parameters
    - camel_case_types
    - non_constant_identifier_names
    - constant_identifier_names
