name: ddd_riverpod
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  auto_route: ^9.2.2
  auto_route_generator: ^9.0.0
  cached_network_image: ^3.4.1
  carousel_indicator: ^1.0.6
  carousel_slider: ^5.0.0
  cupertino_icons: ^1.0.8
  connectivity_plus: ^6.1.1
  device_info_plus: ^11.2.0
  package_info_plus: ^8.1.2
  dartz: ^0.10.1
  dio: ^5.7.0
  mask_text_input_formatter: ^2.9.0

  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.6
  flutter_riverpod: ^2.3.6
  flutter_screenutil: ^5.9.0
  flutter_secure_storage: ^8.0.0
  freezed_annotation: ^2.4.1
  hooks_riverpod: ^2.3.6
  json_annotation: ^4.8.1
  kt_dart: ^1.1.0
  mocktail: ^1.0.3

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.1
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/

  fonts:
    - family: SanFranciscoBold
      fonts:
        - asset: assets/fonts/sanFrancisco/SFUIDisplay-Bold.ttf

    - family: SanFranciscoProBold
      fonts:
        - asset: assets/fonts/sanFrancisco/SF-Pro-Text-Bold.otf

    - family: SanFranciscoProLight
      fonts:
        - asset: assets/fonts/sanFrancisco/SF-Pro-Text-Light.otf

    - family: SanFranciscoProRegular
      fonts:
        - asset: assets/fonts/sanFrancisco/SF-Pro-Text-Regular.otf
